# Generated by Django 5.1.6 on 2025-02-13 13:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название интереса')),
            ],
            options={
                'verbose_name': 'Интерес',
                'verbose_name_plural': 'Интересы',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.CharField(max_length=200, unique=True, verbose_name='Telegram ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя')),
                ('campus', models.CharField(choices=[('1', 'Корпус 1'), ('2', 'Корпус 2'), ('3', 'Корпус 3'), ('4', 'Корпус 4')], max_length=1, verbose_name='Корпус')),
                ('birth_year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2024)], verbose_name='Год рождения')),
                ('gender', models.CharField(choices=[('male', 'Мужской'), ('female', 'Женский')], max_length=10, verbose_name='Пол')),
                ('about_me', models.TextField(blank=True, verbose_name='О себе')),
                ('interests', models.ManyToManyField(blank=True, related_name='students', to='app.interest', verbose_name='Интересы')),
            ],
            options={
                'verbose_name': 'Студент',
                'verbose_name_plural': 'Студенты',
            },
        ),
    ]
