# Generated by Django 5.1.6 on 2025-02-13 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_whom', models.CharField(max_length=200, unique=True, verbose_name='like from')),
                ('to_whow', models.CharField(max_length=200, unique=True, verbose_name='like to')),
            ],
        ),
    ]
