# Generated by Django 5.1.6 on 2025-02-14 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='from_whom',
            field=models.CharField(max_length=200, verbose_name='like from'),
        ),
        migrations.AlterField(
            model_name='like',
            name='to_whow',
            field=models.CharField(max_length=200, verbose_name='like to'),
        ),
    ]
